# Generated by Django 2.1.2 on 2018-10-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='관리자'),
        ),
        migrations.AlterField(
            model_name='user1',
            name='name',
            field=models.CharField(max_length=40, verbose_name='아름'),
        ),
    ]
