# Generated by Django 2.1.2 on 2018-10-18 07:14

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_auto_20181012_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('proxy.user1', models.Model),
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('proxy.user1', models.Model),
            managers=[
                ('items', django.db.models.manager.Manager()),
            ],
        ),
    ]
